# Generated by Django 4.2.5 on 2023-10-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_blog', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Newsletter',
        ),
    ]
